name: heytea_kit_example
description: Demonstrates how to use the heytea_kit plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^1.0.3 #^0.1.3

  # 系统相关
  # https://github.com/theyakka/fluro
  fluro: ^2.0.3 #^1.6.3
  # https://pub.dev/packages/flustars
  flustars: ^2.0.1 #^0.3.2
  # https://pub.dev/packages/intl
  intl: ^0.17.0
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.0.1 #^4.1.0 #^3.0.1 不是最新
  # https://pub.dev/packages/logger
  logger: ^1.0.0 #^0.9.1
  # https://pub.dev/packages/package_info
  package_info: ^2.0.2 #^0.4.0+18
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.0.6 #^0.5.7+2

  # IO相关
  # https://pub.dev/packages/dio
  dio: ^4.0.0 #^3.0.9
  # https://github.com/trevorwang/retrofit.dart/
  retrofit: ^2.0.1 #^1.3.4

  # UI相关
  # https://pub.dev/packages/bot_toast
  bot_toast: ^4.0.1 #^3.0.0
  # https://pub.dev/packages/extended_image
  extended_image: ^4.1.0 #^2.0.0
  # https://pub.dev/packages/flutter_spinkit
  flutter_spinkit: ^5.0.0 #^4.1.2+1
  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^0.22.0 #^0.19.1
  # https://pub.flutter-io.cn/packages/flutter_swiper
  #flutter_swiper: ^1.1.6 #^1.1.6 2019年后没更新了
  #https://pub.dev/packages/flutter_swiper_null_safety
  flutter_swiper_null_safety: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  heytea_kit:
    path: ../

  # https://pub.dev/packages/build_runner
  build_runner: ^2.0.6 #^1.10.0
  # https://pub.dev/packages/intl_translation
  #intl_translation: #^0.17.10+1
  # https://pub.dev/packages/json_serializable
  json_serializable: ^4.1.4 #^5.0.0 #^4.1.3 #^3.3.0 不是最新
  # https://pub.dev/packages/retrofit_generator
  retrofit_generator: ^2.0.1 #^2.0.0+2 #^1.3.4+2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
