name: heytea_kit
description: 喜茶真的不可思议啊~
version: 0.0.1
author:
homepage: https://gitee.com/32250538/netcent_heytea

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  bugly_crash:
    #git:
      # 我们自己fork了一个分支，导出了Bugly的Jar文件
      # https://github.com/DevilLGD/Bugly-Flutter-Plugin
      #url: https://github.com/DevilLGD/Bugly-Flutter-Plugin.git

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^1.0.3 #^0.1.3

  # 系统相关
  # https://pub.dev/packages/decimal
  decimal: ^1.2.0 #^0.3.5
  # https://pub.dev/packages/fake_alipay
  #fake_alipay:
    # 我们自己fork了一个分支，更新了AlipaySDK
    # https://github.com/mingchaogui/fake_alipay
    #git: https://github.com/mingchaogui/fake_alipay.git
  # https://github.com/theyakka/fluro
  fluro: ^2.0.3 #^1.6.3
  # https://pub.dev/packages/fluwx
  #fluwx:
    # 我们自己fork了一个分支，降低了OKHttp版本，以兼容旧有项目
    # https://github.com/DevilLGD/fluwx
    #git: https://github.com/DevilLGD/fluwx.git
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.0.1 #^4.1.0 #^3.0.1 不是最新
  # https://pub.dev/packages/logger
  logger: ^1.0.0 #^0.9.1
  # https://pub.dev/packages/package_info
  package_info: ^2.0.2 #^0.4.0+18
  # https://pub.dev/packages/provider
  provider: ^5.0.0 #^4.1.1
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.0.6 #^0.5.7+2

  # IO相关
  # https://pub.dev/packages/dio
  dio: ^4.0.0 #^3.0.9
  # https://pub.dev/packages/dio_flutter_transformer
  #dio_flutter_transformer: #^3.0.2

  # UI相关
  # https://pub.dev/packages/bot_toast
  bot_toast: ^4.0.1 #^3.0.0
  # https://pub.dev/packages/extended_image
  extended_image: ^4.1.0 #^2.0.0
  # https://pub.dev/packages/flutter_staggered_grid_view
  flutter_staggered_grid_view: ^0.4.0 #^0.3.0
  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^0.22.0 #^0.19.1
  # https://pub.flutter-io.cn/packages/flutter_swiper
  #flutter_swiper: ^1.1.6 #^1.1.6 2019年后没更新了
  #https://pub.dev/packages/flutter_swiper_null_safety
  flutter_swiper_null_safety: ^1.0.2
  # https://pub.dev/packages/flutter_widgets
  #flutter_widgets: ^0.1.12 #^0.1.12 2020年后没更新了
  # https://pub.dev/packages/video_player
  video_player: 2.1.10 #^0.10.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/build_runner
  build_runner: ^ 2.0.6 #^1.10.0
  # https://pub.dev/packages/json_serializable
  json_serializable: ^4.1.4 #^5.0.0 #^4.1.3 #^3.3.0 不是最新

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.laiyou.heytea_kit
    pluginClass: HeyteaKitPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  assets:
    - images/

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
